name: "Release"

description: "Semantically release package"

inputs:
  directory:
    description: "where to run the release"
    required: false
    default: "."
  add_config:
    description: "wether to set default release config"
    required: false
    default: true
  pre_release:
    description: "wether to publish pre-releases from PRs"
    required: false
    default: true
  gh_token:
    description: "A Github PAT"
    required: false
    default: ${{ github.token }}
  npm_token:
    description: "token with which to publish to npm"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        NPM_TOKEN: ${{ inputs.npm_token }}
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
      run: |
        cd ${{ inputs.directory }}

        if [ "${{inputs.add_config}}" = true ]; then
          cp ${{ github.action_path }}/release.config.template.js ./release.config.cjs
        fi

        if [ "${{github.event_name}}" = "push" ]; then
          npx semantic-release@19
        fi

        if [ "${{github.event_name}}" = "pull_request" ] && [ "${{inputs.pre_release}}" = true ]; then
          npm i decorate-gh-pr -D &&
          npx semantish-prerelease@4 --release-pr
        fi
